parentheses = false
square_brackets = true
unstaged_string = "*"
staged_string = "+"
separate_changes = true
remote_icon = true
print_error = false
icon_override = [
        "https://github.com|\ue708",
        "git@github.com|\ue708",
        "https://gitlab.com|\uf296 |252,109,38",
        "git@gitlab.com|\uf296 |252,109,38",
        "git@git.chalmers.se|󰇷|252,109,38"
    ]
icon_color = true
commit_arrow = true
fetch_icon = "󰥔 "
should_fetch = true
fetch_time = 30
commit_behind = ""
commit_ahead = ""
detailed_info = true
detect_nix = true
nix_symbol = "󱄅 "