{ inputs }:
{
  pkgs,
  config,
  nixosConfig,
  ...
}:
{
  home.packages =
    with pkgs;
    [
      firefox
      nixpkgs-fmt
      fastfetch
      protonup-qt
      krita
      obs-studio
      kdePackages.kdenlive
      prismlauncher
      fragments
      wineWow64Packages.stable
      element-desktop
      aisleriot
      chromium
      wl-clipboard
      alacritty
      prettierd
      protontricks
      zenity
      ripgrep
      hunspell
      hunspellDicts.uk_UA
      hunspellDicts.th_TH
      waypipe
      mpv
      zsh-history-substring-search
      obsidian
      fish
      nixfmt
      inkscape
      trayscale
      feishin
      signal-desktop
      gcc
      immich-cli
      openmw
      picard
      cinny-desktop
      easyeffects
      okteta
      beets
    ]
    ++ inputs.git-flakes.packages."${pkgs.system}";
}
