{
  pkgs,
  lib,
  config,
  ...
}:

{
  # Containers
  virtualisation.oci-containers.containers."discodrome" = {
    image = "7eventy7/discodrome:latest";
    environmentFiles = [
      "/home/loafey/Git/compose/discodrome/.env"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=discodrome"
      "--network=discodrome_default"
    ];
  };
  systemd.services."podman-discodrome" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-discodrome_default.service"
    ];
    requires = [
      "podman-network-discodrome_default.service"
    ];
    partOf = [
      "podman-compose-discodrome-root.target"
    ];
    wantedBy = [
      "podman-compose-discodrome-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-discodrome_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f discodrome_default";
    };
    script = ''
      podman network inspect discodrome_default || podman network create discodrome_default
    '';
    partOf = [ "podman-compose-discodrome-root.target" ];
    wantedBy = [ "podman-compose-discodrome-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-discodrome-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
