{ pkgs, lib, config, ... }:
{
  # Containers
  virtualisation.oci-containers.containers."fileflows-fileflows" = {
    image = "revenz/fileflows";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
    };
    volumes = [
      "/mnt/fruit-bowl/services/fileflows:/app/Data:rw"
      "/mnt/fruit-bowl/services/fileflows_temp:/temp:rw"
      "/mnt/fruit-bowl/services/shared/Jellyfin/Movies:/mnt/movies:rw"
      "/mnt/fruit-bowl/services/shared/Jellyfin/Series:/mnt/series:rw"
      "/tmp/podman.sock:/var/run/docker.sock:ro"
    ];
    ports = [
      "8265:5000/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=fileflows"
      "--network=fileflows_default"
    ];
  };
  systemd.services."podman-fileflows-fileflows" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-fileflows_default.service"
    ];
    requires = [
      "podman-network-fileflows_default.service"
    ];
    partOf = [
      "podman-compose-fileflows-root.target"
    ];
    wantedBy = [
      "podman-compose-fileflows-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-fileflows_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f fileflows_default";
    };
    script = ''
      podman network inspect fileflows_default || podman network create fileflows_default
    '';
    partOf = [ "podman-compose-fileflows-root.target" ];
    wantedBy = [ "podman-compose-fileflows-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-fileflows-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
