{
  pkgs,
  lib,
  config,
  ...
}:

{
  # Containers
  virtualisation.oci-containers.containers."img-dump" = {
    image = "tailscale/tailscale:latest";
    environment = {
      "GID" = "1000";
      "TS_STATE_DIR" = "/var/lib/tailscale";
      "TS_USERSPACE" = "true";
      "UID" = "1000";
    };
    volumes = [
      "/dev/net/tun:/dev/net/tun:rw"
      "/mnt/fruit-bowl/services/image-tailscale:/var/lib/tailscale:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cap-add=net_admin"
      "--cap-add=net_raw"
      "--device=/dev/net/tun:/dev/net/tun:rwm"
      "--hostname=img-dump"
      "--network-alias=tailscale-img-dump"
      "--network=img-dump_default"
      "--sysctl=net.ipv4.ip_forward=1"
      "--sysctl=net.ipv6.conf.all.disable_ipv6=1"
    ];
  };
  systemd.services."podman-img-dump" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-img-dump_default.service"
    ];
    requires = [
      "podman-network-img-dump_default.service"
    ];
    partOf = [
      "podman-compose-img-dump-root.target"
    ];
    wantedBy = [
      "podman-compose-img-dump-root.target"
    ];
  };
  virtualisation.oci-containers.containers."img-dump-img-dump" = {
    image = "shish2k/shimmie2:latest";
    environment = {
      "GID" = "1000";
      "UID" = "1000";
    };
    volumes = [
      "/mnt/fruit-bowl/services/image:/app/data:rw"
      # "/mnt/fruit-bowl/services/image/patch.php:/app/index.php:rw"
    ];
    ports = [
      "8000:8000/tcp"
    ];
    dependsOn = [
      "img-dump"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=container:img-dump"
    ];
  };
  systemd.services."podman-img-dump-img-dump" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-img-dump-root.target"
    ];
    wantedBy = [
      "podman-compose-img-dump-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-img-dump_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f img-dump_default";
    };
    script = ''
      podman network inspect img-dump_default || podman network create img-dump_default
    '';
    partOf = [ "podman-compose-img-dump-root.target" ];
    wantedBy = [ "podman-compose-img-dump-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-img-dump-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
