{
  pkgs,
  lib,
  config,
  ...
}:

{
  # Containers
  virtualisation.oci-containers.containers."metadata-remote" = {
    image = "ghcr.io/wow-signal-dev/metadata-remote:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
    };
    volumes = [
      "/mnt/fruit-bowl/services/shared/Jellyfin/Music:/music:rw"
    ];
    ports = [
      "8338:8338/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=[\"wget\", \"--no-verbose\", \"--tries=1\", \"--spider\", \"http://localhost:8338/health\"]"
      "--health-interval=30s"
      "--health-retries=3"
      "--health-start-period=40s"
      "--health-timeout=10s"
      "--network-alias=metadata-remote"
      "--network=podman-metadata_default"
    ];
  };
  systemd.services."podman-metadata-remote" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-podman-metadata_default.service"
    ];
    requires = [
      "podman-network-podman-metadata_default.service"
    ];
    partOf = [
      "podman-compose-podman-metadata-root.target"
    ];
    wantedBy = [
      "podman-compose-podman-metadata-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-podman-metadata_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f podman-metadata_default";
    };
    script = ''
      podman network inspect podman-metadata_default || podman network create podman-metadata_default
    '';
    partOf = [ "podman-compose-podman-metadata-root.target" ];
    wantedBy = [ "podman-compose-podman-metadata-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-podman-metadata-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
