{
  pkgs,
  lib,
  config,
  ...
}:

{
  # Containers
  virtualisation.oci-containers.containers."reverse-proxy" = {
    image = "jc21/nginx-proxy-manager:latest";
    volumes = [
      "/home/loafey/Git/compose/traefik/data:/data:rw"
      "/home/loafey/Git/compose/traefik/letsencrypt:/etc/letsencrypt:rw"
    ];
    ports = [
      "80:80/tcp"
      "81:81/tcp"
      "443:443/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=reverse-proxy"
      "--network=proxy-manager_default"
    ];
  };
  systemd.services."podman-reverse-proxy" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-proxy-manager_default.service"
    ];
    requires = [
      "podman-network-proxy-manager_default.service"
    ];
    partOf = [
      "podman-compose-proxy-manager-root.target"
    ];
    wantedBy = [
      "podman-compose-proxy-manager-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-proxy-manager_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f proxy-manager_default";
    };
    script = ''
      podman network inspect proxy-manager_default || podman network create proxy-manager_default
    '';
    partOf = [ "podman-compose-proxy-manager-root.target" ];
    wantedBy = [ "podman-compose-proxy-manager-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-proxy-manager-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
