{
  pkgs,
  lib,
  config,
  ...
}:

{
  services.udev = {
    enable = true;
    extraRules = ''
      SUBSYSTEM=="tty", ATTRS{idVendor}=="0451", ATTRS{idProduct}=="16a8", MODE="0666"
    '';
  };
  # Containers
  virtualisation.oci-containers.containers."mqtt" = {
    image = "eclipse-mosquitto:latest";
    volumes = [
      "/home/loafey/Git/compose/zigbee/mosquitto-data:/mosquitto:rw"
    ];
    ports = [
      "1883:1883/tcp"
      "9001:9001/tcp"
    ];
    cmd = [
      "mosquitto"
      "-c"
      "/mosquitto-no-auth.conf"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=mqtt"
      "--network=zigbee2mqtt_default"
    ];
  };
  systemd.services."podman-mqtt" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-zigbee2mqtt_default.service"
    ];
    requires = [
      "podman-network-zigbee2mqtt_default.service"
    ];
    partOf = [
      "podman-compose-zigbee2mqtt-root.target"
    ];
    wantedBy = [
      "podman-compose-zigbee2mqtt-root.target"
    ];
  };
  virtualisation.oci-containers.containers."zigbee2mqtt" = {
    image = "koenkk/zigbee2mqtt:1.39.1";
    environment = {
      "PGID" = "0";
      "PUID" = "0";
      "TZ" = "Europe/Berlin";
    };
    volumes = [
      "/home/loafey/Git/compose/zigbee/zigbee2mqtt-data:/app/data:rw"
      "/run/udev:/run/udev:ro"
    ];
    ports = [
      "9002:9002/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--device=/dev/ttyACM0:/dev/ttyACM0:rwm"
      "--network-alias=zigbee2mqtt"
      "--network=zigbee2mqtt_default"
      "--privileged"
      "--security-opt=label=disable"
    ];
  };
  systemd.services."podman-zigbee2mqtt" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-zigbee2mqtt_default.service"
    ];
    requires = [
      "podman-network-zigbee2mqtt_default.service"
    ];
    partOf = [
      "podman-compose-zigbee2mqtt-root.target"
    ];
    wantedBy = [
      "podman-compose-zigbee2mqtt-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-zigbee2mqtt_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f zigbee2mqtt_default";
    };
    script = ''
      podman network inspect zigbee2mqtt_default || podman network create zigbee2mqtt_default
    '';
    partOf = [ "podman-compose-zigbee2mqtt-root.target" ];
    wantedBy = [ "podman-compose-zigbee2mqtt-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-zigbee2mqtt-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
